### ISSUE TITLE
add means of adding custom log entries, preferably derived from the job

### ISSUE THREAD

**Issue by tmc** [Springest/Sidekiq-Logging-JSON#11]

**Comment by bittersweet** [comment]
Hi @tmc , is there any more information you can provide about your idea? How do you see it working?

**Comment by kidbrax** [comment]
Currently by default, it looks as if the job name is not logged or the JID but only the TID. Would be nice to be able to customize that

**Comment by bittersweet** [comment]
Closing this issue because we haven't heard back, let us know if you have more thoughts on this :-)
