### ISSUE TITLE
Sidekiq 6 breaks this gem

### ISSUE THREAD

**Issue by lukaso** [Springest/Sidekiq-Logging-JSON#13]
When loading this gem with sidekiq 6.0, the following error is logged and the gem cannot load.

```
NameError: uninitialized constant Sidekiq::Logging::Pretty
```

The new constant appears to be:

```
Sidekiq::Logger::Formatters::Pretty
```

but I haven't validated that it is a direct switch.

**Comment by bittersweet** [comment]
Hi @lukaso 

I'm not sure this gem is necessary anymore with sidekiq 6.0. We'll be moving to 6.0 soon and are planning on using the builtin logging. From the [6.0 changelog](https://github.com/mperham/sidekiq/blob/0b370e07b2e2e0fc340c321627a7559f9d84bc56/Changes.md#60) :

> Logging has been redesigned to allow for pluggable log formatters:
```
Sidekiq.configure_server do |config|
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new
end
```

I haven't had time yet to test it out and update our readme, but I suspect that will cover everything this gem does.

**Comment by lukaso** [comment]
Thanks, that's really helpful!
