### ISSUE TITLE
Still normal logging

### ISSUE THREAD

**Issue by tweissin-pillpack** [Springest/Sidekiq-Logging-JSON#15]
Hi I tried out this gem. I wasn't sure where to put the initialization commands so I put them in `sidekiq.rb`. I also tried putting them in `environment.rb` and `application.rb` but none work.

The README says to put them in "Sidekiq configuration" but not sure where else that would go.

Thanks!
Tom

**Comment by bittersweet** [comment]
Hi Tom, we have it in our initializer in `config/initializers/sidekiq.rb` so we can confirm that works :-) .
Can you post your full configuration so we can take a look?

I want to note that the newer sidekiq has built-in support for JSON logging, something which might be of interest to you: https://github.com/Springest/Sidekiq-Logging-JSON/issues/13#issuecomment-542300216
