### ISSUE TITLE
Uninitialized constant Sidekiq::Logging::Pretty

### ISSUE THREAD

**Issue by MaHi-A** [Springest/Sidekiq-Logging-JSON#16]
Hi,

After upgrading the `sidekiq` version from 5.2.3 to 6.2.1, sidekiq-logging-json is throwing an exception with uninitialized constant `Sidekiq::Logging::Pretty` while running the server.

![F1272070-C729-4181-94E2-0EC5425769C0_1_201_a](https://user-images.githubusercontent.com/8002680/115333643-a4bf0000-a1b7-11eb-8ff3-aeb990a14290.jpeg)

I've debugged and found that `Sidekiq::Logging::Pretty` class name got changed to `Sidekiq::Logger::Formatters::Pretty`.
https://github.com/mperham/sidekiq/compare/v5.2.3...v6.2.1 

Updating the class name to `Sidekiq::Logger::Formatters::Pretty` would fix the issue.
https://github.com/Springest/Sidekiq-Logging-JSON/blob/master/lib/sidekiq/logging/json.rb#L7

**Comment by bittersweet** [comment]
Hi @MaHi-A , this gem should not be necessary anymore with 6.0, I have not confirmed it myself yet though :-) 

See https://github.com/Springest/Sidekiq-Logging-JSON/issues/13#issuecomment-542300216
